### ISSUE TITLE
Feature Request: one Cluster, multiple node-controller services

### ISSUE THREAD

**Issue by patsch9** [citrix/citrix-k8s-node-controller#33]
related to
#https://github.com/citrix/citrix-helm-charts/issues/136

We want to install multiple node controller to connect a cluster to different vpx's (eg. one VPX for inhouse services and one VPX for external services). For Connection we want to use different subnet, vxlan port and id for each vpx.

At the moment it is not possible, because the clusterRole, clusterRolebinding and Serviceaccount are associated static to "kube-cnc-router". When there is already an installed node-controller, the installation fails, because kube-cnc-router clusterRole, clusterRolebinding and Serviceaccount are alredy exists in another namespace. 

At the second the kube-cnc-router pods where created with fix name schema "kube-cnc-router"+"HOSTNAME". The creation would be failed because there are already existing pods with this name from the first instance.

Possible Solution:
Make the clusterRole, clusterRolebinding and Serviceaccount variable and make a prefix settable for kube-cnc-router pod names.

**Comment by apoorva-05** [comment]
@patsch9 We have addressed this issue in the latest release of Citrix-Node-Controller([v2.2.10](https://github.com/citrix/citrix-k8s-node-controller/releases/tag/v2.2.10)).
UseCase of deploying multiple Instances of Citrix Node Controller in the same cluster is now supported.
For more details please have a look at [Helm Chart Release Notes](https://github.com/citrix/citrix-helm-charts/releases/tag/cnc-v2.2.10).
