### ISSUE TITLE
How to set tolerations for kube-cnc-router pods?

### ISSUE THREAD

**Issue by caruccio** [citrix/citrix-k8s-node-controller#36]
Hello.

I'm installing [citrix-node-controller helm chart](https://github.com/citrix/citrix-helm-charts/tree/master/citrix-node-controller) in a cluster with nodes with `dedicated=effect:NoSchedule` taint.
How can I apply tolerations for the node-specific router pods? There is this file [deploy/configmap_tolerations.yaml](https://github.com/citrix/citrix-k8s-node-controller/blob/master/deploy/configmap_tolerations.yaml) but it seams to be ignored. 
After installing the chart, I've patched the configMap as follow, with no success:

```
$ kubectl get configmap cnc-citrix-node-controller -oyaml
apiVersion: v1
data:
  effect: NoSchedule
  operator: Exists
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: cnc
    meta.helm.sh/release-namespace: citrix
  creationTimestamp: "2023-03-21T14:02:35Z"
  labels:
    app.kubernetes.io/instance: cnc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: citrix-node-controller
    app.kubernetes.io/version: 2.2.10
    helm.sh/chart: citrix-node-controller-2.2.10
  name: cnc-citrix-node-controller
  namespace: citrix
```

The resulting pod spec is alway the same:

```
$ kubectl get pods cnc-kube-cnc-router-kbinfra01 -ojsonpath={.spec.tolerations} | jq
[
  {
    "effect": "NoExecute",
    "key": "node.kubernetes.io/not-ready",
    "operator": "Exists",
    "tolerationSeconds": 300
  },
  {
    "effect": "NoExecute",
    "key": "node.kubernetes.io/unreachable",
    "operator": "Exists",
    "tolerationSeconds": 300
  }
]
```

Thanks.

**Comment by patsch9** [comment]
+1
everytime when i changed the configmap to add the tolarations and redeply the cnc deployment, the configmap changed to the system given values (interfaces, mac addresses, ...)

**Comment by apoorva-05** [comment]
@caruccio @patsch9 We are looking into this. Will keep you updated once this is fixed.

**Comment by dheerajng** [comment]
The issue is resolved.
Please check the release note https://github.com/citrix/citrix-k8s-node-controller/releases/tag/v2.2.11
