### ISSUE TITLE
Limit scheduling of kube-cnc-router pods

### ISSUE THREAD

**Issue by staerion** [citrix/citrix-k8s-node-controller#37]
Hello,

We're trying to leverage the citrix-node-controller to help us configure the routes necessary for the ADC to connect to our kubernetes cluster.

The issue we're running into is that we don't have any options (for as far as we can tell) to limit the scheduling of the kube-cnc-router pods. The only label that appears to be respected to avoid scheduling is "node-role.kubernetes.io/master". However we have split up our kubernetes api servers and etcd servers, so our labels are "node-role.kubernetes.io/controlplane" and "node-role.kubernetes.io/etcd" respectively. Adding the "node-role.kubernetes.io/master" label as a workaround to our nodes doesn't feel right either. 

Is there a possibility to provide an option for more control over to which nodes the kube-cnc-router pods will be scheduled?

Thanks in advance.

**Comment by apoorva-05** [comment]
@staerion Is it possible to taint your nodes in order to prevent CNC router pods from being deployed on them?

**Comment by staerion** [comment]
Hi @apoorva-05 That's what we have currently done, but it results in the kube-cnc-router pods being stuck in status "pending" because they are still created by the node controller but can't be scheduled.

At the same time we have dedicated "database" nodes for which we do need the kube-cnc-router pods, but for these nodes the pods are also stuck in "pending" status because I'm not able to add tolerations to the generatd kube-cnc-router pods.

Would you have any advice on how to proceed?

**Comment by apoorva-05** [comment]
@staerion Was the CNC deployed via yaml file or via helm ?
We do support an option to provide tolerations via configmap https://github.com/citrix/citrix-k8s-node-controller/blob/master/deploy/configmap_tolerations.yaml 
and the helmcharts will be enhanced to accept tolerations as configmap values as well.

**Comment by staerion** [comment]
I've tried both the helm chart and deploying as a yaml file. I did find the option for the configmap_tolerations but it doesn't appear to be used. In the logging of the citrix-node-controller I can see that the configmap being checked for tolerations is the "kube-cnc-router". When I check the code in the pod citrix-node-controller pod itself, it appears that this configmap is being created with the key 'EndpointIP' and 'Type'. It doesn't take any tolerations into account. And this generated configmap is then being checked for the toleration keys.

In the logging of the citrix node controller I then find the loggings:

```
I0613 12:40:11.900934       1 create.go:115] [INFO] Creating Configmap kube-cnc-router
I0613 12:40:12.290981       1 create.go:121] [INFO] Created Configmap kube-cnc-router is &ConfigMap{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:kube-cnc-router,GenerateName:,Namespace:ams-system-citrix,SelfLink:,UID:170f012f-7903-4759-ba10-55859a42f937,ResourceVersion:427075082,Generation:0,CreationTimestamp:2023-06-13 12:40:12 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,ManagedFields:[{citrix-node-controller Update v1 2023-06-13 12:40:12 +0000 UTC nil}],},Data:map[string]string{EndpointIP: 192.128.1.254,Type: VXLAN,},BinaryData:map[string][]byte{},}
I0613 12:40:12.291151       1 create.go:146] [INFO] Reading Configmap kube-cnc-router
I0613 12:40:12.511718       1 create.go:150] [INFO] Configmap info fetched  map[EndpointIP:192.128.1.254 Type:VXLAN]
E0613 12:40:12.511740       1 create.go:168] [ERROR] Invalid Toleration arg: endpointip
E0613 12:40:12.511745       1 create.go:169] [ERROR] Tolerations validation failed, Ignoring Tolerations
```

I'm not sure if I'm doing something wrong, or if there is a mistake with the logic of adding the tolerations to the pods.

**Comment by staerion** [comment]
Hi @apoorva-05 
I have a configmap kube-cnc-router, which is being picked up and configured by the nodecontroller. I hav explicitly set it through the CNC_CONFIGMAP environment variable in the citrix-node-controller deployment.

The node taint is:
```
  taints:
  - effect: NoSchedule
    key: app
    value: elasticsearch
```

What I have tried to set in the kube-cnc-router configmap is:
```
data:
  key: "app"
  operator: "Exists"
  value: "Elasticsaerch"
  effect: "NoSchedule"
  tolerationseconds: "60"
```
When I created this configmap and then restart the citrix-node-controller, I can see in the logging that the kube-cnc-router is being deleted, and regenerated without my settings. And as a result the pods created do not have any tolerations set

After adding the tolerations to the kube-cnc-router configmap:
```
kubectl get cm
kube-cnc-router                33     7m11s
```

I restart the citrix-node-controller and check the logs:

```I0614 11:43:16.953441       1 create.go:83] [INFO] Kubernetes Client is created
I0614 11:43:16.953489       1 delete.go:58] [INFO] Clearing Stale pods and configmaps
I0614 11:43:16.953495       1 delete.go:68] [INFO] Cleaning stale configmap test-kube-cnc-router
I0614 11:43:17.163436       1 delete.go:77] [INFO] Cleaning stale pods created by test-kube-cnc-router...
```

I check the configmap again:

```
kubectl get cm test-kube-cnc-router
NAME                   DATA   AGE
test-kube-cnc-router   28     18s

**Comment by apoorva-05** [comment]
@staerion Please dont modify the kube-cnc-router configmap.
1. If you have deployed Citrix Node Controller using a yaml file
Please create a new configmap with name: citrix-node-controller
```
apiVersion: v1
kind: ConfigMap
apiVersion: v1
metadata:
  name: citrix-node-controller
data:
  key: "app"
  operator: "Exists"
  value: "Elasticsearch"
  effect: "NoSchedule"
  tolerationseconds: "60"
```
2. If you have deployed via helmcharts, you should be seeing  a configmap with name `<helm-release-name>-citrix-node-controller`, you can edit that configmap and update the tolerations.
You can also use the following selector to look for the configmap
```
 kubectl get cm --selector app.kubernetes.io/name=citrix-node-controller
```

**Comment by staerion** [comment]
I have done exactly as you suggest and I can see in the logging that the citrix-node-controller is using the configmap citrix-node-controllerf or its configurations:

```
I0614 13:25:03.902786       1 input.go:476] [INFO] Citrix Node Controller is watching for Configmap= citrix-node-controller, deleting this configmap will instruct the controller to delete the configurations
```

However, I'm still seeing in the logging that the citrix-node-controller is looking at the kube-cnc-router configmap for tolerations:

```
I0614 13:32:58.564778       1 create.go:83] [INFO] Kubernetes Client is created
I0614 13:32:58.564808       1 delete.go:58] [INFO] Clearing Stale pods and configmaps
I0614 13:32:58.564814       1 delete.go:68] [INFO] Cleaning stale configmap kube-cnc-router
I0614 13:32:58.609648       1 delete.go:77] [INFO] Cleaning stale pods created by kube-cnc-router...
I0614 13:32:59.780722       1 create.go:186] [INFO] Creating cnc router configmap and pods
I0614 13:32:59.780741       1 create.go:115] [INFO] Creating Configmap kube-cnc-router
I0614 13:33:00.175547       1 create.go:121] [INFO] Created Configmap kube-cnc-router is &ConfigMap{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:kube-cnc-router,GenerateName:,Namespace:ams-system-citrix,SelfLink:,UID:b4f17db5-286c-492e-9b85-fa2469399bd2,ResourceVersion:222421811,Generation:0,CreationTimestamp:2023-06-14 13:33:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,ManagedFields:[{citrix-node-controller Update v1 2023-06-14 13:33:00 +0000 UTC nil}],},Data:map[string]string{EndpointIP: 192.128.2.254,Type: VXLAN,},BinaryData:map[string][]byte{},}
I0614 13:33:00.175737       1 create.go:146] [INFO] Reading Configmap kube-cnc-router
I0614 13:33:00.374302       1 create.go:150] [INFO] Configmap info fetched  map[EndpointIP:192.128.2.254 Type:VXLAN]
E0614 13:33:00.374496       1 create.go:168] [ERROR] Invalid Toleration arg: type
E0614 13:33:00.374586       1 create.go:169] [ERROR] Tolerations validation failed, Ignoring Tolerations
```

I'm using this deployment.yaml

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: citrix-node-controller
  namespace: test-citrix
  labels:
    app.kubernetes.io/name: citrix-node-controller
    app.kubernetes.io/instance: test
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: citrix-node-controller
      app.kubernetes.io/instance: test
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: citrix-node-controller
        app.kubernetes.io/instance: test
    spec:
      serviceAccountName: citrix-node-controller
      containers:
      - name: citrix-node-controller
        image: "quay.io/citrix/citrix-k8s-node-controller:2.2.10"
        imagePullPolicy: IfNotPresent
        env:
        - name: EULA
          value: "true"
        - name: NS_IP
          value: "10.10.9.9"
        - name: NS_USER
          valueFrom:
            secretKeyRef:
              name: nslogin
              key: username
        - name: NS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nslogin
              key: password
        - name: NETWORK
          value: "192.128.2.0/24"
        - name: REMOTE_VTEPIP
          value: "10.10.10.10"
        - name: VNID
          value: "501"
        - name: VXLAN_PORT
          value: "9091"
        - name: CNI_TYPE
          value: "canal"
        - name: "CLUSTER_NAME"
          value: "test"
        - name: "CNC_ROUTER_NAME"
          value: kube-cnc-router
        - name: "CNC_CONFIGMAP"
          value: citrix-node-controller
```

with this configmap:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: citrix-node-controller
  namespace: test-citrix
data:
  effect: NoSchedule
  key: app
  operator: Exists
  tolerationseconds: "60"
  value: Elasticsearch
```
From the logs it appears that the controller is only looking at the kube-cnc-router configmap for tolerations

**Comment by apoorva-05** [comment]
@staerion Thank you so much for sharing the details. We will have a look and get back to you.

**Comment by staerion** [comment]
Thanks for the quick reponse!

**Comment by staerion** [comment]
Something I realise that is missing from my original request. We also have multiple taints that we need to be tolerated by this pod as we have dedicated nodes with taints for for example elasticsearch or databases.

**Comment by dheerajng** [comment]
This issue is resolved. 
Kindly check out the release note for this enhancement. 
https://github.com/citrix/citrix-k8s-node-controller/releases/tag/v2.2.11
